name = "chittyscrape"
account_id = "0bc21e3a5a9de1a4cc843be9c3e98121"
main = "src/index.ts"
compatibility_date = "2026-01-15"
compatibility_flags = ["nodejs_compat"]

routes = [{ pattern = "scrape.chitty.cc", custom_domain = true }]

[vars]
ENVIRONMENT = "production"

[browser]
binding = "BROWSER"

[[kv_namespaces]]
binding = "SCRAPE_KV"
id = "6d10f7d3727c46b781181d08555f2a7c"

[[tail_consumers]]
service = "chittytrack"
